#!/bin/sh

set -e
set -x

sed -i -e "s/\$RAILS_HOSTNAME/$RAILS_HOSTNAME/g" /etc/nginx/conf.d/default.conf;
sed -i -e "s/\$RAILS_PORT/$RAILS_PORT/g" /etc/nginx/conf.d/default.conf;

nginx -g "daemon off;"
